
spring:
  application:
    name: laymat-demo-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8800/eureka
  server:
    #是否开启安全保护，默认是开启的，如果默认开启，注册中心的服务列表就算有些服务断开了，也会继续保存
    enable-self-preservation: false
server:
  port: 8801
